- name: host lava.aparcar.org
  hosts: lava.aparcar.org
  user: root
  roles:
    - role: common
    - role: lava-server
      name: lava.aparcar.org
      caddy:
        server_name: lava.aparcar.org
        enabled: true
      tags: [lava, caddy]
