---
- name: setup lava jenkins node to run jenkins
  hosts: jenkins-lava
  user: root
  roles:
    - role: common

    - role: jenkins-node
      jenkins_user: jenkins-lava

    - role: jenkins-node
      jenkins_user: virtual-jobs

    - role: lava-tool
