---
- name: install caddy requirements
  apt:
    name: "{{item}}"
  with_items:
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https

- name: add apt key
  apt_key:
    id: ABA1F9B8875A6661
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: add caddy repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main'
    state: present

- name: apt-get update
  apt:
    cache_valid_time: 3600
    update_cache: yes
  changed_when: false

- name: install caddy
  apt:
    name: "{{item}}"
  with_items:
    - caddy

- name: configure lava site
  template:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
  notify: reload caddy
