---
- name: install required packages
  apt:
    name: "{{item}}"
  with_items:
    - python3-pip
    - postgresql
    - git
  tags: [lava]

- name: add apt key
  apt_key:
    id: A791358F2E49B100
    keyserver: pgp.mit.edu
  tags: [lava]

- name: add Lava repository
  apt_repository:
    repo: 'deb https://apt.lavasoftware.org/release {{ ansible_distribution_release }} main'
    state: present
  tags: [lava]

- name: install lava-server and doc
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - lava-server
    - lava-server-doc
  tags: [lava]

- name: disable apache because its a dependency of lava-server
  service:
    name: apache2
    enabled: no
    state: stopped
  failed_when: false
  tags: [lava]

- name: configure lava-server/settings.conf
  template:
    src: lava-server.conf
    dest: /etc/lava-server/settings.conf
    mode: 0640
    group: lavaserver

- import_tasks: caddy.yml
  when: caddy.enabled
  tags: [caddy]

- name: check if /etc/lava-server/dispatcher-config/.git is present
  stat:
    path: /etc/lava-server/dispatcher-config/.git
  register: dispatcher

- name: remove old dispatcher configuration
  file:
    path: /etc/lava-server/dispatcher-config/
    state: absent
  when: dispatcher.stat.exists == false

- name: checking out disaptcher configuration
  git:
    repo: 'https://github.com/aparcar/lava-dispatcher-config.git'
    dest: /etc/lava-server/dispatcher-config/
    clone: yes
    update: yes
    force: yes
    version: mediatek_mt7622_linksys_e8450

