---

- name: install java for stretch
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: yes
    install_recommends: no
  with_items:
    - openjdk-8-jre-headless
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
