---

- name: apt-get update
  apt:
    cache_valid_time: 3600
    update_cache: yes
  changed_when: false

- name: apt-get install lava-tool
  apt:
    name: lava-tool
    install_recommends: yes

- name: install run-lava.sh to /usr/local/bin
  copy:
    src: run-lava-job.sh
    dest: /usr/local/bin/
    mode: 0755
